project:
  type: website

website:
  title: "Synaptic"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Scripts
        menu:
          - href: scripts/qc.qmd
            text: QC
          - href: scripts/atac.qmd
            text: ATAC
          - href: scripts/Additional-ATRT_CellStates.qmd
            text: ATRT Cell States
          - href: scripts/Additional-Pseudobulk_PCA.qmd
            text: Pseudobulk PCA

format:
  html:
    theme: cosmo
    toc: true